apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-depployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-depployment-1
  template:
    metadata:
      labels:
        app: my-depployment-1
    spec:
      containers:
      - name: node
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8085
