apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: "secret-nginx-cert"

      containers:
      - name: n1
        image: taitran89/svc-test:nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: "/certs/"
            name: cert-volume
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 8080 # cong vao port
    targetPort: 80 # cong vao container
    protocol: TCP
    name: http
    nodePort: 31080 #con vao node trong node port
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    nodePort: 31443
