apiVersion: v1
kind: Pod
metadata:
  name: myapp-cluster-ip-1
  labels:
    app: cluster
spec:
  containers:
  - name: n1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name:  myapp-cluster-ip-2
  labels:
    app: cluster
spec:
  containers:
  - name: n1
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80