apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: mypvc1
      containers:
      - name: myapp
        image: busybox
        command:
          - sleep
          - "600"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: "/data"
            name: myvolume