apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    name: ungdung2
    app: app2
    env: dev
spec:
  containers:
  - name: c1
    image: nginx:1.17.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
