apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    name: ungdung1
    app: app1
    env: dev
spec:
  containers:
  - name: c1
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
