variable vpc_cidr_block {}
variable subnet_cidr_block {}
variable avail_zone {}
variable env_prefix {}
variable my_ip {}
variable open_ip {}
variable instance_type {}
variable public_key_location {}
variable private_key_location {}
variable image_name {}
variable target_tag {}
variable snapshot_id {}
variable master_prefix {}
variable worker_prefix {}
variable master_private_ip {}
variable worker_1_private_ip {}
variable worker_2_private_ip {}
variable instance_type_master {}
