variable avail_zone {}
variable env_prefix {}
variable node_bundle_id {}
variable master_bundle_id {}
variable blueprint_id {}
variable open_ip {}
variable public_key_location {}
variable private_key_location {}
variable master_prefix {}
variable worker_prefix {}
variable master_private_ip {}
variable worker_1_private_ip {}
variable worker_2_private_ip {}
variable entry_file {}